name: DevSecOps

on:
  push:
    branches:
      - feature/devsecops

jobs:
  run-bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install bandit
        run: pip install bandit

      - name: SAST - блокировать HIgh severity
        run: bandit -r . --lll

      - name: SAST - предупреждение Medium и Low
        run: bandit -r . -ll --exit-zero
