name: Scan bandit

on:
  pull_request:
    branches:
      - develop

  push:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  run-bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install bandit
        run: pip install bandit

      - name: SAST проверка на HIGH
        run: bandit -r . -lll

      - name: SAST проверка на LOW, MIDLE
        run: bandit -r . -ll --exit-zero

  run-trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      # - name: SCA - run Trivy
      #   run: trivy fs . --scanners vuln --exit-code 1 --severity MEDIUM,HIGH,CRITICAL

      - name: SCA - Trivy scan secrets only
        # if: always()
        run: trivy fs . --exit-code 1
